// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfoNj-2gFN7O1KEiqnDfM19zLUpE_gRMo',
    appId: '1:847807334232:web:dbb266e515e6e151b0472d',
    messagingSenderId: '847807334232',
    projectId: 'teledoctor-base',
    authDomain: 'teledoctor-base.firebaseapp.com',
    storageBucket: 'teledoctor-base.appspot.com',
    measurementId: 'G-V5F0PZ2TWQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5raN2w8wrNcA25JkE09KbaRODoiKXkdI',
    appId: '1:847807334232:android:e2f6d0f40e608778b0472d',
    messagingSenderId: '847807334232',
    projectId: 'teledoctor-base',
    storageBucket: 'teledoctor-base.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEsY1DuoRQwFOrS6asHWkAuHrNTHaPjwU',
    appId: '1:847807334232:ios:64fc04a6b4e7261fb0472d',
    messagingSenderId: '847807334232',
    projectId: 'teledoctor-base',
    storageBucket: 'teledoctor-base.appspot.com',
    iosClientId: '847807334232-7ci065u25ejgk4leup4mkh7uthv4mu6r.apps.googleusercontent.com',
    iosBundleId: 'com.taccetta.teledoctor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEsY1DuoRQwFOrS6asHWkAuHrNTHaPjwU',
    appId: '1:847807334232:ios:64fc04a6b4e7261fb0472d',
    messagingSenderId: '847807334232',
    projectId: 'teledoctor-base',
    storageBucket: 'teledoctor-base.appspot.com',
    iosClientId: '847807334232-7ci065u25ejgk4leup4mkh7uthv4mu6r.apps.googleusercontent.com',
    iosBundleId: 'com.taccetta.teledoctor',
  );
}
